name: SimpleBlocks
version: '${project.version}'
main: me.theoldduck.SimpleBlocks
api-version: 1.16
commands:
  simpbleblocks:
    description: main command
  sbmovehere:
    description: move a block
  sbsetblock:
    description: set a block
  sbeditblock:
    description: edit a block
  sbremoveblock:
    description: remove a block